version: "2"
volumes:
  kafka1volume:
  kafka2volume:
  kafka3volume:
services:
  zookeeper1:
    image: bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
  kafka1:
    image: bitnami/kafka
    container_name: kafka1
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
    ports:
      - "9092"
    depends_on:
      - zookeeper
    volumes:
      - kafka1volume
  kafka2:
    image: bitnami/kafka
    container_name: kafka2
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092"
    volumes:
      - kafka2volume
  kafka3:
    image: bitnami/kafka
    container_name: kafka3
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092"
    volumes:
      - kafka3volume
  spring-app:
    build:
      context: ./sample-kafka-producer
    environment:
      kafka.bootstrapAddress: "kafka1:9092,kafka2:9092,kafka3:9092"
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
#  producer:
#    build: .
#    command: bash -c "sleep 4 && /kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 3 --partitions 2 --topic dates && while true; do date | /kafka/bin/kafka-console-producer.sh --broker-list kafka1:9092,kafka2:9092,kafka3:9092 --topic dates; sleep 1; done "
#    depends_on:
#      - zookeeper
#      - kafka1
#      - kafka2
#      - kafka3
#  consumer:
#    build: .
#    command: bash -c "sleep 6 && /kafka/bin/kafka-console-consumer.sh --topic dates --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092"
#    depends_on:
#      - zookeeper
#      - kafka1
#      - kafka2
#      - kafka3