volumes:
  victoria-volume:
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    command: [ "-retentionPeriod=30d", "-search.maxLookback=720h" ]
    ports:
      - "8428:8428"
    expose:
      - "8428"
    volumes:
      - victoria-volume:/victoria-metrics-data
  vmagent:
    image: victoriametrics/vmagent
    command: ["-promscrape.config=/etc/prometheus/prometheus.yml", "-remoteWrite.url=http://host.docker.internal:8428/api/v1/write"]
    ports:
      - "8429:8429"
    expose:
      - "8429"
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yml
  sample-metrics-test:
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"