global:
  scrape_interval: 5s
remote_write:
  - url: http://host.docker.internal:8428/api/v1/write
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
  - job_name: 'sample-metrics-test'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]